# Generated by Django 4.1.7 on 2023-03-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoTFinModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("asset_manager_positions_long", models.IntegerField()),
                ("asset_manager_positions_short", models.IntegerField()),
                ("change_asset_manager_positions_long", models.IntegerField()),
                ("change_asset_manager_positions_short", models.IntegerField()),
                ("leverage_money_positions_long", models.IntegerField()),
                ("leverage_money_positions_short", models.IntegerField()),
                ("change_leverage_money_positions_long", models.IntegerField()),
                ("change_leverage_money_positions_short", models.IntegerField()),
                (
                    "percentage_of_open_interest_asset_manager_long",
                    models.IntegerField(),
                ),
                (
                    "percentage_of_open_interest_asset_manager_short",
                    models.IntegerField(),
                ),
                (
                    "percentage_of_leverage_money_asset_manager_long",
                    models.IntegerField(),
                ),
                (
                    "percentage_of_leverage_money_asset_manager_short",
                    models.IntegerField(),
                ),
                ("traders_asset_manager_long", models.IntegerField()),
                ("traders_asset_manager_short", models.IntegerField()),
                ("traders_leverage_money_long", models.IntegerField()),
                ("traders_leverage_money_short", models.IntegerField()),
            ],
            options={
                "unique_together": {("currency", "date")},
            },
        ),
    ]
