# Generated by Django 4.1.7 on 2023-03-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traders_commitment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotfinmodel",
            name="asset_manager_positions_long",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cotfinmodel",
            name="asset_manager_positions_short",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cotfinmodel",
            name="change_asset_manager_positions_long",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cotfinmodel",
            name="change_asset_manager_positions_short",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cotfinmodel",
            name="change_leverage_money_positions_long",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cotfinmodel",
            name="change_leverage_money_positions_short",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cotfinmodel",
            name="leverage_money_positions_long",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cotfinmodel",
            name="leverage_money_positions_short",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cotfinmodel",
            name="percentage_of_leverage_money_asset_manager_long",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cotfinmodel",
            name="percentage_of_leverage_money_asset_manager_short",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cotfinmodel",
            name="percentage_of_open_interest_asset_manager_long",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cotfinmodel",
            name="percentage_of_open_interest_asset_manager_short",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cotfinmodel",
            name="traders_asset_manager_long",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cotfinmodel",
            name="traders_asset_manager_short",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cotfinmodel",
            name="traders_leverage_money_long",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cotfinmodel",
            name="traders_leverage_money_short",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
