# Generated by Django 4.1.7 on 2023-03-03 01:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "traders_commitment",
            "0002_alter_cotfinmodel_asset_manager_positions_long_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cotfinmodel",
            unique_together=set(),
        ),
    ]
