# Generated by Django 3.2.9 on 2023-03-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders_commitment', '0003_alter_cotfinmodel_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoTFORScrapedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('file', models.FileField(upload_to='cotfor/')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
