# Generated by Django 3.2.9 on 2023-04-13 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traders_commitment', '0004_cotforscrapedstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoTFin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('asset_manager_positions_long', models.IntegerField(blank=True, null=True)),
                ('asset_manager_positions_short', models.IntegerField(blank=True, null=True)),
                ('change_asset_manager_positions_long', models.IntegerField(blank=True, null=True)),
                ('change_asset_manager_positions_short', models.IntegerField(blank=True, null=True)),
                ('leverage_money_positions_long', models.IntegerField(blank=True, null=True)),
                ('leverage_money_positions_short', models.IntegerField(blank=True, null=True)),
                ('change_leverage_money_positions_long', models.IntegerField(blank=True, null=True)),
                ('change_leverage_money_positions_short', models.IntegerField(blank=True, null=True)),
                ('percentage_of_open_interest_asset_manager_long', models.IntegerField(blank=True, null=True)),
                ('percentage_of_open_interest_asset_manager_short', models.IntegerField(blank=True, null=True)),
                ('percentage_of_leverage_money_asset_manager_long', models.IntegerField(blank=True, null=True)),
                ('percentage_of_leverage_money_asset_manager_short', models.IntegerField(blank=True, null=True)),
                ('traders_asset_manager_long', models.IntegerField(blank=True, null=True)),
                ('traders_asset_manager_short', models.IntegerField(blank=True, null=True)),
                ('traders_leverage_money_long', models.IntegerField(blank=True, null=True)),
                ('traders_leverage_money_short', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('verbose_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('low_price', models.FloatField(blank=True, null=True)),
                ('adj_close_price', models.FloatField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='traders_commitment.currency')),
            ],
        ),
        migrations.DeleteModel(
            name='CoTFinModel',
        ),
        migrations.RemoveField(
            model_name='cotforscrapedstatus',
            name='date',
        ),
        migrations.AddField(
            model_name='cotforscrapedstatus',
            name='is_parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cotforscrapedstatus',
            name='url',
            field=models.TextField(unique=True),
        ),
        migrations.AddField(
            model_name='cotfin',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotfins', to='traders_commitment.currency'),
        ),
    ]
