# Generated by Django 3.2.9 on 2023-04-23 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traders_commitment', '0005_auto_20230413_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotfin',
            options={'verbose_name': 'COT (Financial Reports only) data', 'verbose_name_plural': 'COT (Financial Reports only) data'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='currencyvalue',
            options={'verbose_name': 'Currency value', 'verbose_name_plural': 'Currency values'},
        ),
        migrations.AddField(
            model_name='cotforscrapedstatus',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
