# Generated by Django 3.2.9 on 2023-04-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders_commitment', '0006_auto_20230423_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotfin',
            name='change_asset_manager_positions_long',
        ),
        migrations.RemoveField(
            model_name='cotfin',
            name='change_asset_manager_positions_short',
        ),
        migrations.RemoveField(
            model_name='cotfin',
            name='change_leverage_money_positions_long',
        ),
        migrations.RemoveField(
            model_name='cotfin',
            name='change_leverage_money_positions_short',
        ),
        migrations.RemoveField(
            model_name='cotfin',
            name='traders_asset_manager_long',
        ),
        migrations.RemoveField(
            model_name='cotfin',
            name='traders_asset_manager_short',
        ),
        migrations.RemoveField(
            model_name='cotfin',
            name='traders_leverage_money_long',
        ),
        migrations.RemoveField(
            model_name='cotfin',
            name='traders_leverage_money_short',
        ),
        migrations.AddField(
            model_name='cotfin',
            name='asset_manager_positions_long_short',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotfin',
            name='leverage_money_positions_long_short',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotfin',
            name='other_rept_positions_long_all',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotfin',
            name='other_rept_positions_long_short_all',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotfin',
            name='other_rept_positions_short_all',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotfin',
            name='percentage_of_leverage_money_asset_manager_long_short',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotfin',
            name='percentage_of_open_interest_asset_manager_long_short',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotfin',
            name='percentage_of_other_rept_positions_long_all',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotfin',
            name='percentage_of_other_rept_positions_long_short_all',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotfin',
            name='percentage_of_other_rept_positions_short_all',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
