# Generated by Django 3.2.9 on 2023-04-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders_commitment', '0007_auto_20230423_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyvalue',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
