from typing import List

from indicators.schemas import Frequency, IndicatorSchema
from indicators.countries import AUS


INDICATORS: List[IndicatorSchema] = [
    IndicatorSchema(
        country=AUS,
        name="Business Tendency Surveys for Manufacturing: (Confidence Indicators)",
        code="BSCICP02AUQ460S",
        url="https://fred.stlouisfed.org/series/BSCICP02AUQ460S",
    ),
    IndicatorSchema(
        country=AUS,
        name="Leading Indicator for Production: (BTC OECD Series)",
        code="LOCOBPORAUQ460S",
        url="https://fred.stlouisfed.org/series/LOCOBPORAUQ460S",
        frequency=Frequency.QUARTERLY,
    ),
    IndicatorSchema(
        country=AUS,
        name="PPI Total Manufacturing (2015=100 Index)",
        code="PIEAMP01AUQ661N",
        url="https://fred.stlouisfed.org/series/PIEAMP01AUQ661N",
        frequency=Frequency.QUARTERLY,
    ),
    IndicatorSchema(
        country=AUS,
        name="PPI: Final Demand Services (2009=100 index)",
        code="PPIDSS",
        url="https://fred.stlouisfed.org/series/PPIDSS",
    ),
    IndicatorSchema(
        country=AUS,
        name="PPI: Manufacture of Food Products (2015=100 Index)",
        code="PIEAFD01AUQ661N",
        url="https://fred.stlouisfed.org/series/PIEAFD01AUQ661N",
        frequency=Frequency.QUARTERLY,
    ),
    IndicatorSchema(
        country=AUS,
        name="PPI: Finished Goods (2015=100 Index)",
        code="PISPFG01AUQ661N",
        url="https://fred.stlouisfed.org/series/PISPFG01AUQ661N",
    ),
    IndicatorSchema(
        country=AUS,
        name="Industrial Production Growth Rate (Excluding Construction)",
        code="PRINTO01AUQ657S",
        url="https://fred.stlouisfed.org/series/PRINTO01AUQ657S",
        frequency=Frequency.QUARTERLY,
    ),
    IndicatorSchema(
        country=AUS,
        name="Consumer Sentiment | Confidence (Percentage)",
        code="CSCICP02AUM460S",
        url="https://fred.stlouisfed.org/series/CSCICP02AUM460S",
    ),
    IndicatorSchema(
        country=AUS,
        name="Building Permits: Dwellings | Residential Buildings",
        code="AUSODCNPI03MLSAM",
        url="https://fred.stlouisfed.org/series/AUSODCNPI03MLSAM",
    ),
    IndicatorSchema(
        country=AUS,
        name="New Dwellings | Residential Housing Started Index",
        code="WSCNDW01AUQ661S",
        url="https://fred.stlouisfed.org/series/WSCNDW01AUQ661S",
        frequency=Frequency.QUARTERLY,
    ),
    IndicatorSchema(
        country=AUS,
        name="Total Dwellings | Residential Buildings (Stage of construction in AUD)",
        code="WSCNDW01AUQ189S",
        url="https://fred.stlouisfed.org/series/WSCNDW01AUQ189S",
        frequency=Frequency.QUARTERLY,
    ),
    IndicatorSchema(
        country=AUS,
        name="Residential Property Prices for Australia (Per annum percent)",
        code="QAUN368BIS",
        url="https://fred.stlouisfed.org/series/QAUN368BIS",
        frequency=Frequency.QUARTERLY,
    ),
    IndicatorSchema(
        country=AUS,
        name="Residential Property Prices for Australia (2010=100 Index)",
        code="QAUN628BIS",
        url="https://fred.stlouisfed.org/series/QAUN628BIS",
        frequency=Frequency.QUARTERLY,
    ),
    IndicatorSchema(
        country=AUS,
        name="M1 for Australia (Seasonally Adjusted)",
        code="MANMM101AUM189S",
        url="https://fred.stlouisfed.org/series/MANMM101AUM189S",
    ),
    IndicatorSchema(
        country=AUS,
        name="M3 for Australia (Seasonally Adjusted)",
        code="MABMM301AUM189S",
        url="https://fred.stlouisfed.org/series/MABMM301AUM189S",
    ),
    IndicatorSchema(
        country=AUS,
        name="Broad Money for Australia (Not Seasonally Adjusted)",
        code="BRDMNYAUM189N",
        url="https://fred.stlouisfed.org/series/BRDMNYAUM189N",
    ),
    IndicatorSchema(
        country=AUS,
        name="Real Effective Exchange Rates (CPI deflated)",
        code="CCRETT01AUM661N",
        url="https://fred.stlouisfed.org/series/CCRETT01AUM661N",
    ),
    IndicatorSchema(
        country=AUS,
        name="Consumer Price Index All items (Seasonally Adjusted)",
        code="AUSCPALTT01IXOBSAQ",
        url="https://fred.stlouisfed.org/series/AUSCPALTT01IXOBSAQ",
        frequency=Frequency.QUARTERLY,
    ),
    IndicatorSchema(
        country=AUS,
        name="Consumer Price Index (Less food & energy)",
        code="AUSCPICORQINMEI",
        url="https://fred.stlouisfed.org/series/AUSCPICORQINMEI",
        frequency=Frequency.QUARTERLY,
    ),
    IndicatorSchema(
        country=AUS,
        name="Unemployment Rate: Aged 15 and over(All Persons)",
        code="LRUNTTTTAUM156S",
        url="https://fred.stlouisfed.org/series/LRUNTTTTAUM156S",
    ),
    IndicatorSchema(
        country=AUS,
        name="Employment Rate (All aged 25-54)",
        code="LREM25TTAUM156S",
        url="https://fred.stlouisfed.org/series/LREM25TTAUM156S",
    ),
    IndicatorSchema(
        country=AUS,
        name="Hourly Wage Rate Index (All Activities 2015=100 Index)",
        code="LCWRTT01AUQ661N",
        url="https://fred.stlouisfed.org/series/LCWRTT01AUQ661N",
        frequency=Frequency.QUARTERLY,
    ),
    IndicatorSchema(
        country=AUS,
        name="Total Population (Number of people)",
        code="POPTOTAUA647NWDB",
        url="https://fred.stlouisfed.org/series/POPTOTAUA647NWDB",
        frequency=Frequency.ANNUAL,
    ),
    IndicatorSchema(
        country=AUS,
        name="Retail Sales (in AUD value)",
        code="AUSSARTMDSMEI",
        url="https://fred.stlouisfed.org/series/AUSSARTMDSMEI",
    ),
    IndicatorSchema(
        country=AUS,
        name="Household Debt to GDP",
        code="HDTGPDAUQ163N",
        url="https://fred.stlouisfed.org/series/HDTGPDAUQ163N",
        frequency=Frequency.QUARTERLY,
    ),
    IndicatorSchema(
        country=AUS,
        name="Total Credit to Households & NPISH to GDP (adjusted for breaks)",
        code="CRDQAUAHABIS",
        url="https://fred.stlouisfed.org/series/CRDQAUAHABIS",
        frequency=Frequency.QUARTERLY,
    ),
    IndicatorSchema(
        country=AUS,
        name="Balance of Payments (Value in USD)",
        code="AUSBCABP6USD",
        url="https://fred.stlouisfed.org/series/AUSBCABP6USD",
        frequency=Frequency.ANNUAL,
    ),
    IndicatorSchema(
        country=AUS,
        name="Balance of Payments (Percentage of GDP)",
        code="AUSBCAGDPBP6PT",
        url="https://fred.stlouisfed.org/series/AUSBCAGDPBP6PT",
        frequency=Frequency.ANNUAL,
    ),
    IndicatorSchema(
        country=AUS,
        name="Total Exports (Seasonally Adjusted in USD) ",
        code="XTEXVA01AUM667S",
        url="https://fred.stlouisfed.org/series/XTEXVA01AUM667S",
    ),
    IndicatorSchema(
        country=AUS,
        name="General Government Deb to GDP",
        code="GGGDTAAUA188N",
        url="https://fred.stlouisfed.org/series/GGGDTAAUA188N",
        frequency=Frequency.ANNUAL,
    ),
    IndicatorSchema(
        country=AUS,
        name="10-Year Long-Term Government Bond Yield",
        code="IRLTLT01AUM156N",
        url="https://fred.stlouisfed.org/series/IRLTLT01AUM156N",
    ),
    IndicatorSchema(
        country=AUS,
        name="Interest Rates 3-Month Interbank Rates",
        code="IR3TIB01AUM156N",
        url="https://fred.stlouisfed.org/series/IR3TIB01AUM156N",
    ),
    IndicatorSchema(
        country=AUS,
        name="Interest Rates | Discount Rate",
        code="INTDSRAUM193N",
        url="https://fred.stlouisfed.org/series/INTDSRAUM193N",
        frequency=Frequency.ANNUAL,
    ),
    IndicatorSchema(
        country=AUS,
        name="Real GDP (AUS)",
        code="NGDPRSAXDCAUQ",
        url="https://fred.stlouisfed.org/series/NGDPRSAXDCAUQ",
        frequency=Frequency.QUARTERLY,
    ),
    IndicatorSchema(
        country=AUS,
        name="GDP by Expenditure Total: Constant Prices (AUS)",
        code="AUSGDPRQDSMEI",
        url="https://fred.stlouisfed.org/series/AUSGDPRQDSMEI",
        frequency=Frequency.QUARTERLY,
    ),
    IndicatorSchema(
        country=AUS,
        name="Normalised GDP",
        code="AUSLORSGPNOSTSAM",
        url="https://fred.stlouisfed.org/series/AUSLORSGPNOSTSAM",
    ),
    IndicatorSchema(
        country=AUS,
        name="Volatility of Stock Price Index",
        code="DDSM01AUA066NWDB",
        url="https://fred.stlouisfed.org/series/DDSM01AUA066NWDB",
        frequency=Frequency.ANNUAL,
    ),
]
