# Generated by Django 3.2.9 on 2023-01-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=30)),
                ("date", models.DateField()),
                ("value", models.FloatField(max_length=30)),
                ("unit", models.CharField(blank=True, max_length=125, null=True)),
                (
                    "perc_change",
                    models.FloatField(default=0.0, verbose_name="Percentage of Change"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
