# Generated by Django 3.2.9 on 2023-03-24 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_alter_entry_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='code',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='name',
        ),
        migrations.AlterField(
            model_name='entry',
            name='value',
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[(5, 'Annually'), (1, 'Daily'), (3, 'Monthly'), (4, 'Quarterly'), (2, 'Weekly')], default=3, max_length=20)),
                ('unit', models.CharField(blank=True, max_length=125, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.country')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='indicator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='indicators.indicator'),
            preserve_default=False,
        ),
    ]
