# Generated by Django 3.2.9 on 2023-04-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_auto_20230324_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
