# Generated by Django 3.2.9 on 2023-04-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_alter_country_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'Indicator', 'verbose_name_plural': 'Indicators'},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='perc_change',
            new_name='perc_change1',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='value',
            new_name='value1',
        ),
        migrations.AddField(
            model_name='entry',
            name='perc_change2',
            field=models.FloatField(default=0.0, verbose_name='Percentage of Change (extra)'),
        ),
        migrations.AddField(
            model_name='entry',
            name='perc_change3',
            field=models.FloatField(default=0.0, verbose_name='Percentage of Change (extra)'),
        ),
        migrations.AddField(
            model_name='entry',
            name='total_value',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='value1_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='value2',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='value2_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='value3',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='value3_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
