# Generated by Django 3.2.9 on 2023-04-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_auto_20230423_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='perc_change2',
            field=models.FloatField(blank=True, null=True, verbose_name='Percentage of Change (extra)'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='perc_change3',
            field=models.FloatField(blank=True, null=True, verbose_name='Percentage of Change (extra)'),
        ),
    ]
